name: workout_timer
description: workout_timer
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.2.0
  shared_preferences: ^0.5.4+8
  audioplayers: ^0.13.5
  date_format: ^1.0.8
  url_launcher: ^5.4.1
  wakelock: ^0.1.3+3


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/

  fonts:
    - family: s
      fonts:
        - asset: fonts/s.ttf
    - family: s1
      fonts:
        - asset: fonts/s1.ttf

    - family: s2
      fonts:
        - asset: fonts/s2.ttf

    - family: s3
      fonts:
        - asset: fonts/s3.ttf

    - family: s4
      fonts:
        - asset: fonts/s4.ttf

    - family: s5
      fonts:
        - asset: fonts/s5.ttf

    - family: s6
      fonts:
        - asset: fonts/s6.ttf
    - family: s7
      fonts:
        - asset: fonts/s7.ttf

    - family: s8
      fonts:
        - asset: fonts/s8.ttf

    - family: s9
      fonts:
        - asset: fonts/s9.ttf

    - family: s10
      fonts:
        - asset: fonts/s10.ttf


    - family: d1
      fonts:
        - asset: fonts/d1.ttf

    - family: d2
      fonts:
        - asset: fonts/d2.ttf

    - family: d3
      fonts:
        - asset: fonts/d3.ttf

    - family: d4
      fonts:
        - asset: fonts/d4.ttf

    - family: d5
      fonts:
        - asset: fonts/d5.ttf

    - family: d6
      fonts:
        - asset: fonts/d6.ttf
    - family: d7
      fonts:
        - asset: fonts/d7.ttf

    - family: d8
      fonts:
        - asset: fonts/d8.ttf

    - family: d9
      fonts:
        - asset: fonts/d9.ttf